require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ChaptersController do

  def mock_chapter(stubs={})
    @mock_chapter ||= mock_model(Chapter, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all chapters as @chapters" do
      Chapter.stub(:all) { [mock_chapter] }
      get :index
      assigns(:chapters).should eq([mock_chapter])
    end
  end

  describe "GET show" do
    it "assigns the requested chapter as @chapter" do
      Chapter.stub(:find).with("37") { mock_chapter }
      get :show, :id => "37"
      assigns(:chapter).should be(mock_chapter)
    end
  end

  describe "GET new" do
    it "assigns a new chapter as @chapter" do
      Chapter.stub(:new) { mock_chapter }
      get :new
      assigns(:chapter).should be(mock_chapter)
    end
  end

  describe "GET edit" do
    it "assigns the requested chapter as @chapter" do
      Chapter.stub(:find).with("37") { mock_chapter }
      get :edit, :id => "37"
      assigns(:chapter).should be(mock_chapter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created chapter as @chapter" do
        Chapter.stub(:new).with({'these' => 'params'}) { mock_chapter(:save => true) }
        post :create, :chapter => {'these' => 'params'}
        assigns(:chapter).should be(mock_chapter)
      end

      it "redirects to the created chapter" do
        Chapter.stub(:new) { mock_chapter(:save => true) }
        post :create, :chapter => {}
        response.should redirect_to(chapter_url(mock_chapter))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved chapter as @chapter" do
        Chapter.stub(:new).with({'these' => 'params'}) { mock_chapter(:save => false) }
        post :create, :chapter => {'these' => 'params'}
        assigns(:chapter).should be(mock_chapter)
      end

      it "re-renders the 'new' template" do
        Chapter.stub(:new) { mock_chapter(:save => false) }
        post :create, :chapter => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested chapter" do
        Chapter.stub(:find).with("37") { mock_chapter }
        mock_chapter.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :chapter => {'these' => 'params'}
      end

      it "assigns the requested chapter as @chapter" do
        Chapter.stub(:find) { mock_chapter(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:chapter).should be(mock_chapter)
      end

      it "redirects to the chapter" do
        Chapter.stub(:find) { mock_chapter(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(chapter_url(mock_chapter))
      end
    end

    describe "with invalid params" do
      it "assigns the chapter as @chapter" do
        Chapter.stub(:find) { mock_chapter(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:chapter).should be(mock_chapter)
      end

      it "re-renders the 'edit' template" do
        Chapter.stub(:find) { mock_chapter(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested chapter" do
      Chapter.stub(:find).with("37") { mock_chapter }
      mock_chapter.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the chapters list" do
      Chapter.stub(:find) { mock_chapter }
      delete :destroy, :id => "1"
      response.should redirect_to(chapters_url)
    end
  end

end
