require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CoversController do

  def mock_cover(stubs={})
    @mock_cover ||= mock_model(Cover, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all covers as @covers" do
      Cover.stub(:all) { [mock_cover] }
      get :index
      assigns(:covers).should eq([mock_cover])
    end
  end

  describe "GET show" do
    it "assigns the requested cover as @cover" do
      Cover.stub(:find).with("37") { mock_cover }
      get :show, :id => "37"
      assigns(:cover).should be(mock_cover)
    end
  end

  describe "GET new" do
    it "assigns a new cover as @cover" do
      Cover.stub(:new) { mock_cover }
      get :new
      assigns(:cover).should be(mock_cover)
    end
  end

  describe "GET edit" do
    it "assigns the requested cover as @cover" do
      Cover.stub(:find).with("37") { mock_cover }
      get :edit, :id => "37"
      assigns(:cover).should be(mock_cover)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created cover as @cover" do
        Cover.stub(:new).with({'these' => 'params'}) { mock_cover(:save => true) }
        post :create, :cover => {'these' => 'params'}
        assigns(:cover).should be(mock_cover)
      end

      it "redirects to the created cover" do
        Cover.stub(:new) { mock_cover(:save => true) }
        post :create, :cover => {}
        response.should redirect_to(cover_url(mock_cover))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cover as @cover" do
        Cover.stub(:new).with({'these' => 'params'}) { mock_cover(:save => false) }
        post :create, :cover => {'these' => 'params'}
        assigns(:cover).should be(mock_cover)
      end

      it "re-renders the 'new' template" do
        Cover.stub(:new) { mock_cover(:save => false) }
        post :create, :cover => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cover" do
        Cover.stub(:find).with("37") { mock_cover }
        mock_cover.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :cover => {'these' => 'params'}
      end

      it "assigns the requested cover as @cover" do
        Cover.stub(:find) { mock_cover(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:cover).should be(mock_cover)
      end

      it "redirects to the cover" do
        Cover.stub(:find) { mock_cover(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(cover_url(mock_cover))
      end
    end

    describe "with invalid params" do
      it "assigns the cover as @cover" do
        Cover.stub(:find) { mock_cover(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:cover).should be(mock_cover)
      end

      it "re-renders the 'edit' template" do
        Cover.stub(:find) { mock_cover(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cover" do
      Cover.stub(:find).with("37") { mock_cover }
      mock_cover.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the covers list" do
      Cover.stub(:find) { mock_cover }
      delete :destroy, :id => "1"
      response.should redirect_to(covers_url)
    end
  end

end
