require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DetailsController do

  def mock_detail(stubs={})
    @mock_detail ||= mock_model(Detail, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all details as @details" do
      Detail.stub(:all) { [mock_detail] }
      get :index
      assigns(:details).should eq([mock_detail])
    end
  end

  describe "GET show" do
    it "assigns the requested detail as @detail" do
      Detail.stub(:find).with("37") { mock_detail }
      get :show, :id => "37"
      assigns(:detail).should be(mock_detail)
    end
  end

  describe "GET new" do
    it "assigns a new detail as @detail" do
      Detail.stub(:new) { mock_detail }
      get :new
      assigns(:detail).should be(mock_detail)
    end
  end

  describe "GET edit" do
    it "assigns the requested detail as @detail" do
      Detail.stub(:find).with("37") { mock_detail }
      get :edit, :id => "37"
      assigns(:detail).should be(mock_detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created detail as @detail" do
        Detail.stub(:new).with({'these' => 'params'}) { mock_detail(:save => true) }
        post :create, :detail => {'these' => 'params'}
        assigns(:detail).should be(mock_detail)
      end

      it "redirects to the created detail" do
        Detail.stub(:new) { mock_detail(:save => true) }
        post :create, :detail => {}
        response.should redirect_to(detail_url(mock_detail))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved detail as @detail" do
        Detail.stub(:new).with({'these' => 'params'}) { mock_detail(:save => false) }
        post :create, :detail => {'these' => 'params'}
        assigns(:detail).should be(mock_detail)
      end

      it "re-renders the 'new' template" do
        Detail.stub(:new) { mock_detail(:save => false) }
        post :create, :detail => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested detail" do
        Detail.stub(:find).with("37") { mock_detail }
        mock_detail.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :detail => {'these' => 'params'}
      end

      it "assigns the requested detail as @detail" do
        Detail.stub(:find) { mock_detail(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:detail).should be(mock_detail)
      end

      it "redirects to the detail" do
        Detail.stub(:find) { mock_detail(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(detail_url(mock_detail))
      end
    end

    describe "with invalid params" do
      it "assigns the detail as @detail" do
        Detail.stub(:find) { mock_detail(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:detail).should be(mock_detail)
      end

      it "re-renders the 'edit' template" do
        Detail.stub(:find) { mock_detail(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested detail" do
      Detail.stub(:find).with("37") { mock_detail }
      mock_detail.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the details list" do
      Detail.stub(:find) { mock_detail }
      delete :destroy, :id => "1"
      response.should redirect_to(details_url)
    end
  end

end
